name: scrapcrafters
description: "ScrapCrafters - AI-Powered Circular Economy Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  http: ^1.2.0
  provider: ^6.1.0
  google_fonts: ^8.0.2
  image_picker: ^1.1.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_spinkit: ^5.2.1
  google_maps_flutter: ^2.10.0
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/logo.jpeg"
  adaptive_icon_background: "#0A1929"
  adaptive_icon_foreground: "assets/logo/logo.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - .env
